[package]
name = "finch-types"
version.workspace = true
edition.workspace = true

[dependencies]
half.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
