[package]
name = "finch-memory"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
finch-db.workspace = true
finch-types.workspace = true
parking_lot.workspace = true
pgvector = { version = "0.4.2", features = ["postgres"], optional = true }
postgres = { version = "0.19.14", optional = true }
serde.workspace = true
serde_json.workspace = true

[features]
postgres = ["dep:postgres", "dep:pgvector"]
